title: Belkirk College of Engineering
short_title: Belkirk
description: Belkirk Demo Site for Forestry.io
cloudinary_url: https://res.cloudinary.com/rustycloud/image/upload
baseurl: 
sass:
  sass_dir: assets/css/sass
permalink: /:categories/:year/:title
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  collections_dir: content
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
    permalink: "/:categories/:year/:title"
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-menus
  # - jekyll-feed
  # - jekyll-archives
