---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: about.md
  label: About
  match: "**/*"
- type: heading
  label: Content
- type: directory
  path: content/_posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/_projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - project
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
